name: terra_zero_waste_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  video_player: ^2.2.18
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: any
  get: ^4.6.6
  google_fonts: ^6.2.1

  firebase_core: any
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  uuid: ^4.4.0
  timeago: ^3.6.1
  cached_network_image: ^3.3.1
  flutter_toggle_tab: ^1.4.1
  awesome_dialog: ^3.2.1
  flutter_slidable: ^3.1.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  confetti: ^0.7.0
  dash_chat_2: ^0.0.21
  flutter_gemini: ^2.0.4
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/images/login_page.png
   - lib/assets/images/background_login_page.jpg
   - lib/assets/images/zero_waste_image_1.jpg
   - lib/assets/images/women_profile_pic.jpg
   - lib/assets/images/zero_waste_image_2.jpg
   - lib/assets/images/men_profile_pic.jpg
   - lib/assets/images/qr_code.png

   - lib/assets/images/composting_task.jpg
   - lib/assets/images/reusable_bag.jpg
   - lib/assets/images/carpool.jpg
   - lib/assets/images/donation.jpg
   - lib/assets/images/public_transport.jpg
   - lib/assets/images/tank_water.jpg
   - lib/assets/images/water_bottle.jpg
   - lib/assets/images/cleaning.jpg
   - lib/assets/images/meal_plan.jpg
   - lib/assets/images/green_vege.jpg
   - lib/assets/images/voucher.jpg
   - lib/assets/images/gardening.jpg
   - lib/assets/images/person.png
   - lib/assets/images/chat.png
   - lib/assets/images/search.png
   - lib/assets/images/logo.png

   - lib/assets/images/google_sign_in.png

   



   - lib/assets/gif_icons/earth.gif
   - lib/assets/gif_icons/mother-earth-day.gif
   - lib/assets/gif_icons/history.gif
   - lib/assets/gif_icons/list.gif
   - lib/assets/gif_icons/money-bag.gif
   - lib/assets/gif_icons/high_five.gif
   - lib/assets/gif_icons/coupon.gif

   - lib/assets/gif_icons/composting.gif
   - lib/assets/gif_icons/shopping_bag.gif
   - lib/assets/gif_icons/charity.gif
   - lib/assets/gif_icons/mini-car.gif
   - lib/assets/gif_icons/water.gif
   - lib/assets/gif_icons/train.gif
   - lib/assets/gif_icons/meal_plan.gif
   - lib/assets/gif_icons/bottle.gif
   - lib/assets/gif_icons/plant.gif
   - lib/assets/gif_icons/cleaning.gif
   - lib/assets/gif_icons/coffee-cup.gif
   - lib/assets/gif_icons/clapperboard.gif
   - lib/assets/gif_icons/basket.gif
   - lib/assets/gif_icons/10-percent.gif
   - lib/assets/gif_icons/tick.gif
   - lib/assets/gif_icons/search_icon.gif
   - lib/assets/gif_icons/image_icon.gif
   - lib/assets/gif_icons/caption_icon.gif
   - lib/assets/gif_icons/camera_flash_icon.gif
   - lib/assets/gif_icons/chatbot_icon.gif
   - lib/assets/gif_icons/earth_banner_icon.gif
   - lib/assets/gif_icons/edit_profile_icon.gif
   - lib/assets/gif_icons/log_out_icon.gif
   - lib/assets/gif_icons/organic_splash.gif


   - assets/images/logo.png

   
   - lib/assets/json/tick.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
